- name: Install multiple packages using loop
  hosts: webservers
  become: yes

  tasks:
    - name: Install common packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - curl
        - vim
        - htop

